sudo: required
services:
  - docker

before_install:
  - docker build -t hasheminasab/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run hasheminasab/react-test npm test -- --coverage

after_success:
  - docker build -t hasheminasab/multi-client ./client
  - docker build -t hasheminasab/multi-nginx ./nginx
  - docker build -t hasheminasab/multi-server ./server
  - docker build -t hasheminasab/multi-worker ./worker
  # log in to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push hasheminasab/multi-client
  - docker push hasheminasab/multi-nginx
  - docker push hasheminasab/multi-server
  - docker push hasheminasab/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-279817822427
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY