sudo: required
services:
  - docker

before_install:
  - docker build -t Alireza/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run Alireza/react-test npm test -- --coverage

after_success:
  - docker build -t Alireza/multi-client ./client
  - docker build -t Alireza/multi-nginx ./nginx
  - docker build -t Alireza/multi-server ./server
  - docker build -t Alireza/multi-worker ./worker
  # log in to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push Alireza/multi-client
  - docker push Alireza/multi-nginx
  - docker push Alireza/multi-server
  - docker push Alireza/multi-worker
